name: supeats
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.9
  firebase_dynamic_links: ^4.3.8
  firebase_messaging: ^13.0.3

  get_it: ^7.2.0

  flutter_riverpod: ^1.0.4

  go_router: ^5.0.1

  easy_localization: ^3.0.1
  adaptive_theme: ^3.1.1

  websafe_svg: ^2.1.2+4

  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true